/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.yourcompany.struts.bean.GoodsInfotable;
import com.yourcompany.struts.dao.GoodsInfoDao;
import com.yourcompany.struts.form.goodsForm;

/** 
 * MyEclipse Struts
 * Creation date: 07-20-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class GoodsAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward allgoods(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
			GoodsInfoDao goods=new GoodsInfoDao();
	        ArrayList al = goods.all();
			request.setAttribute("al", al);
		    return mapping.findForward("allgoods");
		
		}
	
	
	
	public ActionForward addgoods(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		goodsForm goodsForm = (goodsForm) form;
		GoodsInfotable goods=new GoodsInfotable();
		
		goods.setGoodsId(goodsForm.getGoodsId());
		goods.setGoodsName(goodsForm.getGoodsName());
		goods.setGoodsClassId(goodsForm.getGoodsClassId());
		goods.setSuppliersId(goodsForm.getSuppliersId());
	    goods.setGoodsProductPlace(goodsForm.getGoodsProductPlace());
	    goods.setGoodsPrice(goodsForm.getGoodsPrice());
	    goods.setModelOfGoods(goodsForm.getModelOfGoods());
	    goods.setVolumeOfGoods(goodsForm.getVolumeOfGoods());
	    
	    GoodsInfoDao goodsinfodao =new GoodsInfoDao();
	    try
		{
			boolean bool = goodsinfodao.add(goods);
			
			if (!bool)
			{
				return mapping.findForward("addgoods");
			}
		}
		catch(Exception e)
		{
			e.printStackTrace();
		}
		return null;
	}
	public ActionForward delgoods(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		String goods = request.getParameter("goodsId");
		
		System.out.println("googdsId========" + goods);
		GoodsInfoDao goodsinfodao =new GoodsInfoDao();
		boolean b = goodsinfodao.del(goods);
		System.out.println("++++++++");
		if (b){
			return mapping.findForward("delgoods");
		}
		return null;
	}
	
}