/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.yourcompany.struts.bean.InstoreInfotable;
import com.yourcompany.struts.dao.InstoreInfoDao;

/** 
 * MyEclipse Struts
 * Creation date: 07-21-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class InstoreInfoAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward allinstore(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		InstoreInfoDao goods=new InstoreInfoDao();
	        ArrayList al = goods.all();
			request.setAttribute("al", al);
		    return mapping.findForward("allinstore");
		
		}
	
	public ActionForward delinstore(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		String goods = request.getParameter("districtId");
		
		InstoreInfoDao instoreinfodao=new InstoreInfoDao();
		boolean b = instoreinfodao.del(goods);
		System.out.println("++++++++");
		if (b){
			return mapping.findForward("delinstore");
		}
		return null;
	}
	public ActionForward allstore(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		InstoreInfoDao goods=new InstoreInfoDao();
	        ArrayList al = goods.all();
			request.setAttribute("al", al);
		    return mapping.findForward("allstore");
		
		}
	public ActionForward getId(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
	
		String uid = request.getParameter("districtId");
		System.out.println("id=========" + uid);
		InstoreInfoDao goods=new InstoreInfoDao();
		try
		{
			InstoreInfotable good = goods.getId(uid);
			
			System.out.println(good.getDistrictName());
			
			request.setAttribute("goods",good);
		}
		catch(Exception e)
		{
			e.printStackTrace();
		}
		
		return mapping.findForward("getId");
	}
	
	public ActionForward updstore(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String Id=request.getParameter("districtId");
		
		System.out.println("id=========" + Id);
		String userName=request.getParameter("districtVolume");
		String password=request.getParameter("goodVolumeMax");
		String address=request.getParameter("goodVolumeMin");
		InstoreInfoDao goods=new InstoreInfoDao();
		try
		{
			boolean a=goods.updUser(Id,userName,password,address);
		
		}
		catch(Exception e)
		{
			e.printStackTrace();
		}
		return mapping.findForward("updstore");
	}
	
}