/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.yourcompany.struts.dao.GoodsInfoDao;
import com.yourcompany.struts.dao.InvoiceInfoDao;

/** 
 * MyEclipse Struts
 * Creation date: 07-23-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class InvoiceAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward allout(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		InvoiceInfoDao userDao = new InvoiceInfoDao();
		ArrayList list =userDao.view();
		request.setAttribute("list", list);
		System.out.println("======================cccccccccccccccc");
		return mapping.findForward("allout");

	}
	
	public ActionForward updout(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		String goods = request.getParameter("goodsId");	
		InvoiceInfoDao userDao = new InvoiceInfoDao();
		boolean b = userDao.upd(goods);
		System.out.println("++++++++");
		if (b){
			return mapping.findForward("updout");
		}
		return null;
	}
	
}