/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.yourcompany.struts.bean.EmployeeInfotable;
import com.yourcompany.struts.dao.Login;
import com.yourcompany.struts.form.LoginForm;

/** 
 * MyEclipse Struts
 * Creation date: 07-19-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws SQLException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response){
		// TODO Auto-generated method stub
		LoginForm loginForm=(LoginForm) form;
		String employeeId=loginForm.getEmployeeId();
		String password=loginForm.getPassword();
		
		EmployeeInfotable em=new EmployeeInfotable();
		Login login=new Login();
		em=login.login(employeeId, password);
		HttpSession session = request.getSession();
		session.setAttribute("em", em);
		int i=em.getLoginPower();
		System.out.println("type======" + i);
			if(i==1)
			{
				return mapping.findForward("success3");
			}
			else
			{
				if(i==2)
				{
					return mapping.findForward("success1");
				}
				else
				{
					return mapping.findForward("success2");
				}
			}	
	}
}