/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.yourcompany.struts.Exception.AppException;
import com.yourcompany.struts.bean.EmployeeInfotable;
import com.yourcompany.struts.dao.OperaterecordDao;
import com.yourcompany.struts.dao.StockIninDao;

/** 
 * MyEclipse Struts
 * Creation date: 07-23-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class PdAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward addpd(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		System.out.println("shibai==============");
		    OperaterecordDao ord=new OperaterecordDao();
		    HttpSession session = request.getSession();
			EmployeeInfotable em = (EmployeeInfotable) session.getAttribute("em");
			// 获得当前用户ID
			String employeeId = em.getEmployeeId();
		    String goodsName=(String)request.getParameter("select");
		    goodsName = new String(goodsName.getBytes("ISO-8859-1"),"gbk");
		    String num=request.getParameter("goodsNum");
		    String type="盘点";
		    String time = new SimpleDateFormat("yyyyMMddHHmmss").format(Calendar.getInstance().getTime());
		    ord.addpd(employeeId, type, time, goodsName, num);
			return mapping.findForward("pdsuccess");
		}
	public ActionForward viewpd(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws Exception{
		    OperaterecordDao ord=new OperaterecordDao();
			ArrayList list =ord.viewpd();
			request.setAttribute("list", list);
			return mapping.findForward("viewpd");
		}
}