/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 07-20-2010
 * 
 * XDoclet definition:
 * @struts.form name="supplierForm"
 */
public class SupplierForm extends ActionForm {
	String suppliersId;
	String suppliersName;
	String suppliersChargePerson;
	String suppliersLocation;
	String suppliersTel;
	String suppliersEmail;
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public String getSuppliersId() {
		return suppliersId;
	}

	public void setSuppliersId(String suppliersId) {
		this.suppliersId = suppliersId;
	}

	public String getSuppliersName() {
		return suppliersName;
	}

	public void setSuppliersName(String suppliersName) {
		this.suppliersName = suppliersName;
	}

	public String getSuppliersChargePerson() {
		return suppliersChargePerson;
	}

	public void setSuppliersChargePerson(String suppliersChargePerson) {
		this.suppliersChargePerson = suppliersChargePerson;
	}

	public String getSuppliersLocation() {
		return suppliersLocation;
	}

	public void setSuppliersLocation(String suppliersLocation) {
		this.suppliersLocation = suppliersLocation;
	}

	public String getSuppliersTel() {
		return suppliersTel;
	}

	public void setSuppliersTel(String suppliersTel) {
		this.suppliersTel = suppliersTel;
	}

	public String getSuppliersEmail() {
		return suppliersEmail;
	}

	public void setSuppliersEmail(String suppliersEmail) {
		this.suppliersEmail = suppliersEmail;
	}
}