/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import org.apache.struts.action.ActionForm;

public class UpdateuserpasswordForm extends ActionForm{
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String oldpassword;
	private String newpassword;
	private String connewpassword;
	public String getOldpassword() {
		return oldpassword;
	}
	public void setOldpassword(String oldpassword) {
		this.oldpassword = oldpassword;
	}
	public String getNewpassword() {
		return newpassword;
	}
	public void setNewpassword(String newpassword) {
		this.newpassword = newpassword;
	}
	public String getConnewpassword() {
		return connewpassword;
	}
	public void setConnewpassword(String connewpassword) {
		this.connewpassword = connewpassword;
	}

}